Repository Herta-villa/Herta-villa-SDK, pull requests merged in 2023-08, with the labels that each got.

#38 Docs: 增加贡献指南，贡献者公约和问题模板
  .github/ISSUE_TEMPLATE/api-changed.yml
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  hertavilla/apis/audit.py
  hertavilla/apis/auth.py
  hertavilla/apis/emoticon.py
  hertavilla/apis/img.py
  hertavilla/apis/internal.py
  hertavilla/apis/member.py
  hertavilla/apis/message.py
  hertavilla/apis/role.py
  hertavilla/apis/room.py
  hertavilla/apis/villa.py
  hertavilla/message/chain.py
  hertavilla/message/image.py
  hertavilla/message/internal.py
  hertavilla/message/post.py
  hertavilla/message/text.py
  hertavilla/utils.py
  tests/test_utils.py
Labels: 📝documentation

#41 0.8.1
  .github/ISSUE_TEMPLATE/api-changed.yml
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/release_configuration.json
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  hertavilla/apis/audit.py
  hertavilla/apis/auth.py
  hertavilla/apis/emoticon.py
  hertavilla/apis/img.py
  hertavilla/apis/internal.py
  hertavilla/apis/member.py
  hertavilla/apis/message.py
  hertavilla/apis/role.py
  hertavilla/apis/room.py
  hertavilla/apis/villa.py
  hertavilla/bot.py
  hertavilla/message/chain.py
  hertavilla/message/image.py
  hertavilla/message/internal.py
  hertavilla/message/post.py
  hertavilla/message/text.py
  hertavilla/utils.py
  tests/test_utils.py
Labels: release

#42 :sparkles: 链接消息支持 `requires_bot_access_token`
  hertavilla/message/text.py
Labels: ✨feature

#44 :memo: 在 README 中添加 FOSSA 许可证扫描状态
  README.md
Labels: 📝documentation

#45 0.8.2
  .github/release_configuration.json
  README.md
  hertavilla/message/text.py
Labels: release

#47 :sparkles: 审核 api 更新支持 content_type
  hertavilla/apis/audit.py
  hertavilla/model.py
Labels: ✨feature
